### ISSUE TITLE
What is the rational?

### ISSUE THREAD

**Issue by runeimp** [sindresorhus/macos-term-size#4]
I'm curious what use case you had where the terminal size was needed but not available, such as in a non-interactive shell?

BTW, you can use the POSIX standard utility `stty` , on everything but Windows from what I can tell, to get the terminal size.

### Subwindow of KiTTY

```bash
$ stty size
35 128
$ stty size &> x; cat x
35 128
```

#### If you just want the cols

```bash
$ stty size | cut -d' ' -f2
128
```

### iTerm2

```bash
$ stty size
25 78
$ stty size &> x; cat x
25 78
```

### tmux in iTerm2

```bash
$ tput cols
78
$ tput lines
24
$ stty size
24 78
$ stty size &> x; cat x
24 78
```

### Apple Terminal

```zsh
$ tput cols 
120
$ tput lines
36
$ stty size            
36 120
$ stty size &> x; cat x
36 120
```

**Comment by Alhadis** [comment]
I came here to point this out too.

Note that it's also possible to query the dimensions of terminal windows *other* than the current one:

~~~console
$ stty -f /dev/ttys001 size
$ stty -f "`tty`" size
~~~

**Comment by jpmhouston** [comment]
"Rationale"?

Not (just) trying to be an a**hat, I seriously couldn't figure out what the title meant before opening and thought it was math related.

Nonetheless, up-voted.

**Comment by sindresorhus** [comment]
I needed it for [`term-size`](https://github.com/sindresorhus/term-size).

---

```js
// x.js
const childProcess = require('child_process');

childProcess.execFile('stty', ['size'], (error, stdout) => {
	console.log(error || stdout);
});
```

```
$ node x.js
Error: Command failed: stty size
stty: stdin isn't a terminal

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'stty size'
}
```

**Comment by Alhadis** [comment]
Try this:

~~~js
const childProcess = require("child_process");

const {stdout: tty} = childProcess.spawnSync("tty", {
	stdio: ["inherit", "pipe", "inherit"],
	encoding: "utf8",
});

childProcess.execFile("stty", ["-f", tty.trim(), "size"], (error, stdout) => {
	console.log(error || stdout);
});
~~~

However, it's much easier to use the getters that Node.js provides natively:

~~~js
const size =
	process.stdout.isTTY ? [process.stdout.columns, process.stdout.rows] :
	process.stderr.isTTY ? [process.stderr.columns, process.stderr.rows] :
	process.stdin.isTTY  ? [process.stdin.columns,  process.stdin.rows]  :
	null;
~~~

**Comment by sindresorhus** [comment]
1. It cannot use `inherit` as that could potentially output stuff directly to the users terminal, and a reusable package should not do that.
2. It has to work even if the code spawning `stty` is spawned itself. Meaning multiple levels of spawning.
3. `process.stdout.columns` is undefined if it's in a spawned file.

---

The point of this binary is to get the columns and rows no matter what.

**Comment by Alhadis** [comment]
> It cannot use `inherit` as that could potentially output stuff directly to the users terminal

Not if you're `inherit`ing only the standard input stream:

~~~diff
 const {stdout: tty} = childProcess.spawnSync("tty", {
-	stdio: ["inherit", "pipe", "inherit"],
+	stdio: ["inherit", "pipe", "pipe"],
 	encoding: "utf8",
 });
~~~

The [`stdio` array](https://nodejs.org/dist/latest-v16.x/docs/api/child_process.html#child_process_options_stdio) pertains to STDIN, STDOUT, and STDERR, respectively.

**Comment by sindresorhus** [comment]
Closing as this is no longer used by `term-size`: https://github.com/sindresorhus/terminal-size/releases/tag/v4.0.0
